version: '3'
services:
  nextjs:
    build: ./frontend-nextjs
    volumes:
      - ./frontend-nextjs:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'

  flask:
    build: ./text-classification
    restart: always
    ports:
      - '5000:5000'
    volumes: 
      - ./text-classification:/app
    environment:
      - FLASK_ENV=development

volumes:
  database:
    driver: local
