import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [form, setForm] = useState({});
  const [commentInfo, setCommentInfo] = useState({});

  const check = async comment => {
    const res = await fetch('/api/predict?comment=' + comment);
    const data = await res.json();
    setCommentInfo(data);
  }

  const handleSubmit = event => {
    event.preventDefault();
    const { comment } = form;
    check(comment);
  }

  const handleChange = event => {
    setForm({...form, [event.target.name]: event.target.value});
    check(event.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>is my comment ok?</title>
        <meta name="description" content="Generated by is my comment ok?" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a Is my comment ok?
        </h1>

        <form className={styles.card} onSubmit={handleSubmit}>
          <div className="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <input className="border-2 border-indigo-600 px-4 py-2 rounded-full w-full focus:outline-none focus:ring-4 ring-indigo-300" name="comment" placeholder="Escribe tu comentario" onChange={handleChange}/>
            <br/>
            <br/>
            <button className="bg-indigo-600 bg-opacity-75 rounded-full px-6 py-1 text-white font-bold" type="submit">Enviar</button>
          </div>
        </form>
        {Object.keys(commentInfo).length > 0 && form.comment && (
          <p className={styles.description}>
            Este comentario es {commentInfo.result ? 'bueno' : 'malo'}. {commentInfo.acc.toFixed(3)}
          </p>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Docker.
        </a>
      </footer>
    </div>
  )
}
